import Link from "next/link";
import { notFound } from "next/navigation";
import { loadAllRecaps, loadRecap } from "@/lib/recaps";
import { loadSeason } from "@/lib/data";
import { buildTeamMeta } from "@/lib/awards";

export function generateStaticParams() {
  return loadAllRecaps().map((r) => ({ year: r.season, week: String(r.week) }));
}

export default async function RecapPage({
  params,
}: {
  params: Promise<{ year: string; week: string }>;
}) {
  const { year, week } = await params;
  const recap = loadRecap(year, Number(week));
  if (!recap) notFound();

  const season = loadSeason(year);
  const teams = buildTeamMeta(season);
  const teamByName = new Map<string, ReturnType<typeof teams.get>>();
  for (const [, t] of teams) teamByName.set(t.teamName.toLowerCase(), t);

  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <Link href="/recaps" className="text-white/40 hover:text-white/80 text-sm">
        ← All Recaps
      </Link>

      <article className="mt-6">
        <div className="text-sm uppercase tracking-[0.2em] text-white/40 mb-3">
          {recap.season} · Week {recap.week}
        </div>
        <h1 className="text-4xl md:text-5xl font-black tracking-tight leading-tight mb-4">
          {recap.headline}
        </h1>
        <p className="text-xl text-white/70 mb-10 leading-relaxed">
          {recap.subhead}
        </p>

        <section className="card-glow p-6 mb-8">
          <div className="text-xs uppercase tracking-wider text-white/60 mb-2">
            Match of the Week
          </div>
          <p className="text-white/90 leading-relaxed">{recap.matchOfTheWeek}</p>
        </section>

        <section className="prose prose-invert max-w-none mb-10">
          {recap.mainRecap.split(/\n\n+/).map((para, i) => (
            <p key={i} className="text-white/80 leading-relaxed text-lg mb-4">
              {para}
            </p>
          ))}
        </section>

        <section className="card p-6 mb-8">
          <div className="text-xs uppercase tracking-wider text-white/60 mb-2">
            Power Rankings
          </div>
          <p className="text-white/80">{recap.powerRankingsShakeup}</p>
        </section>

        <section className="mb-12">
          <h2 className="text-sm uppercase tracking-[0.2em] text-white/40 mb-4">
            Weekly Awards
          </h2>
          <div className="grid gap-3 sm:grid-cols-2">
            {recap.weeklyAwards.map((a, i) => {
              const t = teamByName.get(a.team.toLowerCase());
              return (
                <div key={i} className="card p-4">
                  <div className="text-xs uppercase tracking-wider text-accent mb-1">
                    {a.title}
                  </div>
                  <div className="flex items-center gap-2 mb-2">
                    {t?.avatar ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={t.avatar} alt="" className="w-6 h-6 rounded-full object-cover" />
                    ) : (
                      <div className="w-6 h-6 rounded-full bg-white/10" />
                    )}
                    <span className="font-bold">{a.team}</span>
                  </div>
                  <p className="text-sm text-white/70 leading-snug">{a.blurb}</p>
                </div>
              );
            })}
          </div>
        </section>

        <footer className="text-xs text-white/30 border-t border-white/5 pt-6">
          Generated by {recap.modelId} on {new Date(recap.generatedAt).toLocaleDateString()}
        </footer>
      </article>
    </main>
  );
}
